@startuml blueprint

actor User
boundary Server
control Service

Server -> Server: create shared memory
Server -> Server: open loopback tcp

Service -> Server: connect to loopback tcp
Server -> Service: accept connection
Server -> Service: send shared memory id
Service -> Service: open shared memory

loop job
    User -> Server: request
    Server -> Service: send header

    loop send and receive
        Server -> Server: copy to shared memory
        Service -> Service: send current size
        Service -> Service: copy from shared memory
        Service -> Server: send read size
    end
end

@enduml